
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: buildings-db
      POSTGRES_USER: buildings-user
      POSTGRES_PASSWORD: buildings-password
    ports:
      - 5432:5432