
version: '3.1'

services:
  api:
    build:
      context: buildings-api
      dockerfile: dockerfile
    image: buildings-api
    volumes:
      - ./settings.yml:/app/settings.yml:ro
    depends_on:
      - db
    ports:
      - "9090:8080"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: buildings-db
      POSTGRES_USER: buildings-user
      POSTGRES_PASSWORD: buildings-password
    ports:
      - 5432:5432